service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demoeks-svc
  namespace: dm-eks
  labels:
     app: demoeks
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: demoeks
