apiVersion: v1
kind: Service
metadata:
  name: "service-nginx-albdemo"
  namespace: "alb-demo"
  labels:
    app: nginx-albdemo
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /usr/share/nginx/html/index.html
spec:
  ports:
    - port: 81
      targetPort: 81
      protocol: TCP
  type: NodePort
  selector:
    app: "nginx-albdemo"
